application: send2cloud-server
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /bootstrap
  static_dir: bootstrap

- url: /stylesheets
  static_dir: stylesheets

- url: /work
  script: server.app
  login: admin

- url: /set_app_token
  script: admin.app
  login: admin

- url: /.*
  script: server.app

libraries:
- name: jinja2
  version: latest
